### ISSUE TITLE
pyintro | Example Calculation in Public library

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#35]
Objective: I want to know the resistivity of seawater with salinity. See example table below. Using the table below, if I give a value of salinity, I should get appropriate resistivity.

![image](https://github.com/vamseeachanta/digitalmodel/assets/23155845/77af25df-6a8f-4b81-a9c1-ea2f21583ebb)
Ref: https://github.com/vamseeachanta/digitalmodel/blob/4815e2bdf86e427283343c1fa47814f88f27e0b5/docs/cathodic_protection/literature/course_notes_Appendix_A_Cathodic_Protection_Design.pdf (See page 17)

Please see below example on how to develop, maintain and publish a public library:
https://github.com/vamseeachanta/py_package

**Comment by samdansk2** [comment]
### Subject: Daily Progress Notes 
Date   : 30-01-2024

Dear Vamsee sir,
I wanted to provide you with an update on my progress today :

1. GitHub Public Libraries :
   - Explored best practices for maintaining public libraries on GitHub.
   - Reviewed issue tracking, pull requests and etc.....

2. Specific conductance Problem :
   - spent much time to understand this problem clearly first 
   - Got to know that specific conductance is the reciprocal of resistivity and to find the resistivity of seawater 
     with a given salinity and temperature :

         Resistivity (Ωm) = 1 / Specific Conductance (S/m)
     
     For example, if the salinity of the seawater is 35 parts per thousand (ppt) and the temperature is 15°C
     the specific conductance from the table is 0.042024 S/m. Therefore, the resistivity would be:

         Resistivity = 1 / 0.042024 S/m = 23.8 Ωm
      
3. GitHub Repository 
   - forked the original repository to try first 
   - after that created a new repository called Task-1.

Looking forward to your insights,

Thankyou.

**Comment by samdansk2** [comment]
### Subject: Daily Progress Notes 
Date   : 30-01-2024
Dear Vamsee sir,

I wanted to provide you with an update on my progress today :

1. GitHub Public Libraries :
   - Explored best practices for maintaining public libraries on GitHub.
   - Reviewed issue tracking, pull requests etc ....

2. Specific conductance Problem :
   - spent much time to understand this problem clearly first 
   - Specific conductance is the reciprocal of resistivity and to find the resistivity of seawater 
     with a given salinity and temperature :
     Resistivity = 1/ specific conductance
     
     For example, if the salinity of the seawater is 35 parts per thousand (ppt) and the temperature is 15°C
     the specific conductance from the table is 0.042024 S/m. Therefore, the resistivity would be:
     Resistivity = 1/0.042024 = 23.8 Ωm
     
3. GitHub Repository 
   - forked the original repository to try first 
   - after that created a new repository called Task-1.

Looking forward to your insights,

Thankyou.

**Comment by samdansk2** [comment]
### Date : 31- 01- 2024

Hello sir , Good Morning ,
Today's progress is as follows :

-->  Started with the problem  to know about how to compute the specific conductance .
        the relationship between temperature , salinity with specific conductance .
       
        the basic formula is " Specific conductance = 1 / Resistance " , but as we are dealing with temp and salinity
        sp_conductance = base_conductance * (1 + alpha * salinity - beta * (temperature - 25))
        where alpha , beta and base_conductance are constant values .

--> Coming to code ,
      -- wrote a function to address the problem 
      -- according to the formula specific conductance is computed 
      -- took input of both temperature and salinity 
      -- the resistivity is also computed as it is the reciprocal of specific conductance  

-->  Created a new repository called Task-1 
     -- Added the folder of py_package into my repository where it has three files init,main,calculation.py
     --  used git for this process 
     -- Cloned the repository in Vscode and  wrote a code 
     --  staged all changes , commited the message .

    that's all for today sir ,
    Thankyou .

**Comment by vamseeachanta** [comment]
Great proactive start. You got good place holders for folder and code structure. Keep it up. When you made the calculation happen, let me know and I will guide you further.

**Comment by samdansk2** [comment]
Here it is the Repository link  :  https://github.com/samdansk2/Task-1/tree/main/src/py_package

please see it sir , once you can go through it .

**Comment by samdansk2** [comment]
> Great proactive start. You got good place holders for folder and code structure. Keep it up. When you made the calculation happen, let me know and I will guide you further.

Thankyou sir , Sure sir , next time i will take guidance from you

**Comment by vamseeachanta** [comment]
@samdansk2 Let us wrap this work up next time we meet.

**Comment by samdansk2** [comment]
@vamseeachanta 

Already I have completed this, eveything is going well including local tests and GitHub actions workflow. Please once check it out with below link
https://github.com/samdansk2/ace
After pushing this to pypi.org we can close this issue
