### ISSUE TITLE
Prepare plots for project report

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#39]
- Utilize virtual environment and code from below branch
  - https://github.com/vamseeachanta/assetutilities/tree/2024
- Run below visualizations and see if plots have appeared:
  - https://github.com/vamseeachanta/assetutilities/blob/2024/src/assetutilities/tests/test_visualization_xy_line_matplotlib_csv.py
  - https://github.com/vamseeachanta/assetutilities/blob/2024/src/assetutilities/tests/test_visualization_xy_line_matplotlib_input.py
- Prepare new visualizations for project.

**Comment by vamseeachanta** [comment]
@saiachanta2728 @samdansk2

Please can you try to do the the above tasks one by one? Need help for a project work to prepare charts etc.

**Comment by samdansk2** [comment]
Sir , do not understand  what to do , how to do and
where can run the visulalizations .

**Comment by vamseeachanta** [comment]
@samdansk2 . I added the files to run (See my edits above). 
First thing is to create virtual environment in Conda using command prompt.

**Comment by samdansk2** [comment]
Sure sir 👍

**Comment by samdansk2** [comment]
figured out the errors during installation and other things

**Comment by samdansk2** [comment]
assetutilities and other engine modules are not being recognizable

**Comment by vamseeachanta** [comment]
@samdansk2 @saiachanta2728 
see if this latest environment file works:
https://github.com/vamseeachanta/assetutilities/blob/2024/dev_tools/environment.yml

Command: 
conda env update -f environment.yml
