### ISSUE TITLE
Organization Copilot membership

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#48]
ID: support@aceengineer.com
password: 

https://github.com/pricing

https://github.com/edu/students

**Comment by vamseeachanta** [comment]
@samdansk2 , 
- register github copilot as student ID
  - https://github.com/edu/students
- You may need to combine your university ID with personal ID in github profile to use the copilot
- Test copilot

**Comment by samdansk2** [comment]
@vamseeachanta 

Done sir , got access to student developer pack benifits ,
installed copilot in VScode from extensions and also it is working great .
