### ISSUE TITLE
dev | Consolidate MES file messages

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#49]
Summarize .MES file warnings and errors 
- Read the errors and warnings in .MES files
- Count & combine them using machine learning or NLP.
- Summarize common errors
- Summarize the errors from multiple .MES files in meaningful manner

**Comment by vamseeachanta** [comment]
example .MES files are given below:
https://github.com/vamseeachanta/digitalmodel/tree/orcaflex_analysis/src/digitalmodel/tests/test_data/aqwa/mes_files

**Comment by samdansk2** [comment]
@vamseeachanta 
Done sir , i am attaching the drive link below , please see it
https://docs.google.com/document/d/1BASQbS3CmKf38VY5hjkxwUIYVE3_iule/edit?usp=drive_link&ouid=105838564713965623513&rtpof=true&sd=true

**Comment by vamseeachanta** [comment]
@samdansk2. Looks very good as starting point. Please do share the code for this.
We need to do this repeatedly in a given project or different projects. Hence we need to the same in a programmatical manner to summarize errors.

An example table we are looking for is in link below. A screenshot is given for convenience:
https://github.com/vamseeachanta/digitalmodel/blob/orcaflex_analysis/docs/pkg_ansys/aqwa/aqwa_run_errors.md#mes-file-comparison

![image](https://github.com/vamseeachanta/digitalmodel/assets/23155845/40f5e673-8fb8-4c9e-a0c3-dfb8c0e4166d)


CC: @swamypolnati

**Comment by samdansk2** [comment]
@vamseeachanta 
added the code sir , please see it

github.com/vamseeachanta/digitalmodel/blob/orcaflex_analysis/src/digitalmodel/custom/aqwa/mes_files.py

**Comment by vamseeachanta** [comment]
#TODO
- dataframe with columns: Type, Description, Frequency, Files (see template code)
- 
Long-term
- Convert to class function
- Integrate into digitalmodel

**Comment by samdansk2** [comment]
@vamseeachanta 
everything is done sir ,

- as you said above , created comparison table 
- Dataframe created 
- converted into csv files 
- warnings.csv and errors.csv

**Comment by vamseeachanta** [comment]
Good work. Please see work:
- granularity of each warning or error in .MES files
-

**Comment by samdansk2** [comment]
@vamseeachanta 

Done sir , check it out 

- https://github.com/vamseeachanta/digitalmodel/blob/0622e8a21e96b108bb075d5d37227a922a46b2e5/warning_error_map.csv
-

**Comment by samdansk2** [comment]
@vamseeachanta Hi sir , 
Bug fixed , you can check it out below ,
https://github.com/vamseeachanta/digitalmodel/blob/7f503471bd7e79c19ebb3a10f848144a6e773bad/src/digitalmodel/custom/aqwa/mes_files.py

**Comment by vamseeachanta** [comment]
- Reviewed code
- Merged all OrcaFlex analysis into master (Too many commits)
- Created new branch 202409
- Added 2 tests for with mes files and no mes files
- Added color font for print. Look at the examples and continue using the same format.
-

**Comment by vamseeachanta** [comment]
*This was generated by AI during triage.*

**Flagged `model-rework` (2026-06-10):** ABANDONED-NOW-CHEAP — summarizing AQWA .MES warnings/errors was attempted with manual NLP/ML and a one-off script + Google doc; a current model does this trivially and well. Re-executing as a solver-diagnostics summarizer would slot into the sanity-checked-output stage of epics #622/#689. Flag register: see triage session 2026-06-10.
