### ISSUE TITLE
Time Series: Reduce .csv file size footprint

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#66]
- Decrease output footprint helps. Each run is generating 100 MB to 300 MB sized files. (team programming effort). 
- [ ] ideal custom round-off; tests. (Not Done. Punted as this is long term engineering stuff)

 - [x] Round 1: CSV files is the output; crude round-off; driven from configuration files;
- [x] Customize code to handle 1 hour and 3 hour runs using input file

**Comment by getsivakumar** [comment]
@vamseeachanta  completed 2 tasks. as discussed, please take over task 3.

**Comment by vamseeachanta** [comment]
will add a story when need arises. No business user is interested in advancing this.
