### ISSUE TITLE
small bug | when executing from gitbash colorama text coloring in python is not showing up.

### ISSUE THREAD

**Issue by getsivakumar** [vamseeachanta/digitalmodel#68]

**Comment by vamseeachanta** [comment]
should we consider switching to a more supported library long-term?
https://realpython.com/python-rich-package/

**Comment by getsivakumar** [comment]
lets try to fix it ...

if that fails we can switch .

Regards

Sivakumar Pabolu

**Comment by vamseeachanta** [comment]
explore loguru 
utilize git bash to color text for critical distinction
