### ISSUE TITLE
optimization | dependency management 

### ISSUE THREAD

**Issue by getsivakumar** [vamseeachanta/digitalmodel#70]
migrate repo from to poetry from miniconda and pip 

need following info from @vamseeachanta 
- [ ] Sample test cases that will prepare input blocks for OrcaFlex 
  - [ ] Run reliability checks
    - [x] In individual session
    - [ ] Demo and handover test runs in a joint session
  - [ ] show test cases run via vscode
  - [ ] show test cases run via gitbash
- [ ] siva to then refactor to poetry

**Comment by vamseeachanta** [comment]
Please see below test cases:
https://github.com/vamseeachanta/digitalmodel/blob/2f90260282109473ddc930d08f81ed37dba34a43/tests/modules/code_dnvrph103/test_code_dnvrph103.py
https://github.com/vamseeachanta/digitalmodel/blob/2f90260282109473ddc930d08f81ed37dba34a43/tests/modules/pipeline/test_pipeline.py

**standard architecture - ways to run:**
python {.py test file}
python -m digitalmodel {.yml file}

the embedded yml files in tests:
https://github.com/vamseeachanta/digitalmodel/blob/2f90260282109473ddc930d08f81ed37dba34a43/tests/modules/code_dnvrph103/118kgbuoy.yml
https://github.com/vamseeachanta/digitalmodel/blob/2f90260282109473ddc930d08f81ed37dba34a43/tests/modules/pipeline/pipeline_lateral_bucklng.yml

**Comment by vamseeachanta** [comment]
added as tech debt here: https://github.com/vamseeachanta/assetutilities/issues/32
