### ISSUE TITLE
script to customize orcaflex runs 

### ISSUE THREAD

**Issue by getsivakumar** [vamseeachanta/digitalmodel#73]
- need a script - preferably shell script. if not powershell 
- can set / unset / remove windows registry entries 
- in this case, specific windows registry entry is 

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Orcina\OrcaFlex]
"DefaultThreadCount"=dword:0000000c

meta question.. what is the best tool from a devops perspective to manage windows registry ? 

- [ ] update 12/4 - did troubleshooting. use admin mode. call for more questions.

**Comment by getsivakumar** [comment]
takeaways 

- just write a PS or gitbash script for now 
- in future, worth looking at ansible for configuration management (if you have to manage many servers.. for a single server, individual scripts are fine) 

research 

``@google reddit what is most reputed windows devops tool to manage registry``
ansible (a bit of an overkill for now..) 
salt (again well reputed.. but a bit of an overkill, for this) 
PS etc/SCCM/DSC (pre ansible, i guess)

[search](https://www.google.com/search?q=windows+devops+configuration+management+light+weight+)

**Comment by getsivakumar** [comment]
hi @vamseeachanta finished checking in a file.

**Comment by getsivakumar** [comment]
hi @vamseeachanta as discussed, use in admin mode.

**Comment by vamseeachanta** [comment]
completed by correcting the hexadecimal number.
