### ISSUE TITLE
OrcaFlex | ThreadCount PowerShell Script

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#74]
- first cut code done
- see error below
-

**Comment by vamseeachanta** [comment]
![image](https://github.com/user-attachments/assets/2c10553d-a741-49ff-8685-0b6add9a3164)

**Comment by getsivakumar** [comment]
hi @vamseeachanta I tried this on my local machine. I had to run this in a (admin mode) powershell. Could you try that ?

**Comment by vamseeachanta** [comment]
code was invalid. Updated the numeric code and it worked. Good job there mate.
