### ISSUE TITLE
OrcaFlex | Model Status update

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/digitalmodel#76]
Prepare model status flowchart with font in red where analysis is still ongoing. 
Prepare PUML file.

**Comment by getsivakumar** [comment]
hi @vamseeachanta 

here are the flowcharts we discussed. 

https://github.com/vamseeachanta/digitalmodel/blob/823aa11aaf9d74a61e21a18afe559438d51917a3/docs/pkg_orcaflex/notes/pre_model/vessels/multibody_model.png

https://github.com/vamseeachanta/digitalmodel/blob/7b2f6442acf3ebe1cb3e39d3fa31d9fdab813998/docs/pkg_orcaflex/notes/pre_model/pre_model_dynamics.png
